# Docker Compose v1 format for very old Docker Compose versions (1.17.x)
yolo-seed-detection:
  build: .
  dockerfile: Dockerfile.jetson-fixed
  container_name: yolo-seed-detector
  restart: unless-stopped
  privileged: true
  environment:
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    - DISPLAY=:0
    - QT_X11_NO_MITSHM=1
    - PYTHONUNBUFFERED=1
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev:/dev
    - ./logs:/app/logs
    - ./data:/app/data
    - ./calibration:/app/calibration:ro
  devices:
    - /dev/video0:/dev/video0
    - /dev/video1:/dev/video1
    - /dev/ttyUSB0:/dev/ttyUSB0
    - /dev/ttyACM0:/dev/ttyACM0
  net: host
  log_driver: "json-file"
  log_opt:
    max-size: "100m"
    max-file: "3"