# Docker Compose v1 format for Docker Compose 1.17.x on Jetson Nano
# Ultra-minimal configuration to avoid repository issues

yolo-seed-detection:  build: .
  container_name: yolo-seed-detector-minimal
  restart: unless-stopped
  privileged: true
  environment:
    - DISPLAY=:0
    - QT_X11_NO_MITSHM=1
    - PYTHONUNBUFFERED=1
    - NVIDIA_VISIBLE_DEVICES=all
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev:/dev
    - ./logs:/app/logs
    - ./data:/app/data
    - ./models:/app/models
  devices:
    - /dev/video0:/dev/video0
    - /dev/video1:/dev/video1
    - /dev/video2:/dev/video2
  net: host
