# Test configuration for Docker Compose v1.17.x
# Uses absolute minimum configuration and no system packages

yolo-seed-detection:
  build: .
  dockerfile: Dockerfile.test
  container_name: yolo-test
  privileged: true
  environment:
    - DISPLAY=:0
    - QT_X11_NO_MITSHM=1
    - PYTHONUNBUFFERED=1
  volumes:
    - /tmp/.X11-unix:/tmp/.X11-unix:rw
    - /dev:/dev
    - ./logs:/app/logs
    - ./data:/app/data
  devices:
    - /dev/video0:/dev/video0
    - /dev/video1:/dev/video1
  net: host
