"""
This type stub file was generated by pyright.
"""

from ultralytics.utils.torch_utils import smart_inference_mode

"""
Check a model's accuracy on a test or val split of a dataset.

Usage:
    $ yolo mode=val model=yolo11n.pt data=coco8.yaml imgsz=640

Usage - formats:
    $ yolo mode=val model=yolo11n.pt                 # PyTorch
                          yolo11n.torchscript        # TorchScript
                          yolo11n.onnx               # ONNX Runtime or OpenCV DNN with dnn=True
                          yolo11n_openvino_model     # OpenVINO
                          yolo11n.engine             # TensorRT
                          yolo11n.mlpackage          # CoreML (macOS-only)
                          yolo11n_saved_model        # TensorFlow SavedModel
                          yolo11n.pb                 # TensorFlow GraphDef
                          yolo11n.tflite             # TensorFlow Lite
                          yolo11n_edgetpu.tflite     # TensorFlow Edge TPU
                          yolo11n_paddle_model       # PaddlePaddle
                          yolo11n.mnn                # MNN
                          yolo11n_ncnn_model         # NCNN
                          yolo11n_imx_model          # Sony IMX
                          yolo11n_rknn_model         # Rockchip RKNN
"""
class BaseValidator:
    """
    BaseValidator.

    A base class for creating validators.

    Attributes:
        args (SimpleNamespace): Configuration for the validator.
        dataloader (DataLoader): Dataloader to use for validation.
        pbar (tqdm): Progress bar to update during validation.
        model (nn.Module): Model to validate.
        data (dict): Data dictionary.
        device (torch.device): Device to use for validation.
        batch_i (int): Current batch index.
        training (bool): Whether the model is in training mode.
        names (dict): Class names.
        seen: Records the number of images seen so far during validation.
        stats: Placeholder for statistics during validation.
        confusion_matrix: Placeholder for a confusion matrix.
        nc: Number of classes.
        iouv: (torch.Tensor): IoU thresholds from 0.50 to 0.95 in spaces of 0.05.
        jdict (dict): Dictionary to store JSON validation results.
        speed (dict): Dictionary with keys 'preprocess', 'inference', 'loss', 'postprocess' and their respective
                      batch processing times in milliseconds.
        save_dir (Path): Directory to save results.
        plots (dict): Dictionary to store plots for visualization.
        callbacks (dict): Dictionary to store various callback functions.
    """
    def __init__(self, dataloader=..., save_dir=..., pbar=..., args=..., _callbacks=...) -> None:
        """
        Initializes a BaseValidator instance.

        Args:
            dataloader (torch.utils.data.DataLoader): Dataloader to be used for validation.
            save_dir (Path, optional): Directory to save results.
            pbar (tqdm.tqdm): Progress bar for displaying progress.
            args (SimpleNamespace): Configuration for the validator.
            _callbacks (dict): Dictionary to store various callback functions.
        """
        ...
    
    @smart_inference_mode()
    def __call__(self, trainer=..., model=...):
        """Executes validation process, running inference on dataloader and computing performance metrics."""
        ...
    
    def match_predictions(self, pred_classes, true_classes, iou, use_scipy=...): # -> Tensor:
        """
        Matches predictions to ground truth objects (pred_classes, true_classes) using IoU.

        Args:
            pred_classes (torch.Tensor): Predicted class indices of shape(N,).
            true_classes (torch.Tensor): Target class indices of shape(M,).
            iou (torch.Tensor): An NxM tensor containing the pairwise IoU values for predictions and ground of truth
            use_scipy (bool): Whether to use scipy for matching (more precise).

        Returns:
            (torch.Tensor): Correct tensor of shape(N,10) for 10 IoU thresholds.
        """
        ...
    
    def add_callback(self, event: str, callback): # -> None:
        """Appends the given callback."""
        ...
    
    def run_callbacks(self, event: str): # -> None:
        """Runs all callbacks associated with a specified event."""
        ...
    
    def get_dataloader(self, dataset_path, batch_size):
        """Get data loader from dataset path and batch size."""
        ...
    
    def build_dataset(self, img_path):
        """Build dataset."""
        ...
    
    def preprocess(self, batch):
        """Preprocesses an input batch."""
        ...
    
    def postprocess(self, preds):
        """Preprocesses the predictions."""
        ...
    
    def init_metrics(self, model): # -> None:
        """Initialize performance metrics for the YOLO model."""
        ...
    
    def update_metrics(self, preds, batch): # -> None:
        """Updates metrics based on predictions and batch."""
        ...
    
    def finalize_metrics(self, *args, **kwargs): # -> None:
        """Finalizes and returns all metrics."""
        ...
    
    def get_stats(self): # -> dict[Any, Any]:
        """Returns statistics about the model's performance."""
        ...
    
    def check_stats(self, stats): # -> None:
        """Checks statistics."""
        ...
    
    def print_results(self): # -> None:
        """Prints the results of the model's predictions."""
        ...
    
    def get_desc(self): # -> None:
        """Get description of the YOLO model."""
        ...
    
    @property
    def metric_keys(self): # -> list[Any]:
        """Returns the metric keys used in YOLO training/validation."""
        ...
    
    def on_plot(self, name, data=...): # -> None:
        """Registers plots (e.g. to be consumed in callbacks)."""
        ...
    
    def plot_val_samples(self, batch, ni): # -> None:
        """Plots validation samples during training."""
        ...
    
    def plot_predictions(self, batch, preds, ni): # -> None:
        """Plots YOLO model predictions on batch images."""
        ...
    
    def pred_to_json(self, preds, batch): # -> None:
        """Convert predictions to JSON format."""
        ...
    
    def eval_json(self, stats): # -> None:
        """Evaluate and return JSON format of prediction statistics."""
        ...
    


