"""
This type stub file was generated by pyright.
"""

from ultralytics.models import yolo

class OBBTrainer(yolo.detect.DetectionTrainer):
    """
    A class extending the DetectionTrainer class for training based on an Oriented Bounding Box (OBB) model.

    Example:
        ```python
        from ultralytics.models.yolo.obb import OBBTrainer

        args = dict(model="yolo11n-obb.pt", data="dota8.yaml", epochs=3)
        trainer = OBBTrainer(overrides=args)
        trainer.train()
        ```
    """
    def __init__(self, cfg=..., overrides=..., _callbacks=...) -> None:
        """Initialize a OBBTrainer object with given arguments."""
        ...
    
    def get_model(self, cfg=..., weights=..., verbose=...): # -> OBBModel:
        """Return OBBModel initialized with specified config and weights."""
        ...
    
    def get_validator(self): # -> OBBValidator:
        """Return an instance of OBBValidator for validation of YOLO model."""
        ...
    


