"""
This type stub file was generated by pyright.
"""

def on_pretrain_routine_start(trainer): # -> None:
    """Runs at start of pretraining routine; initializes and connects/ logs task to ClearML."""
    ...

def on_train_epoch_end(trainer): # -> None:
    """Logs debug samples for the first epoch of YOLO training and report current training progress."""
    ...

def on_fit_epoch_end(trainer): # -> None:
    """Reports model information to logger at the end of an epoch."""
    ...

def on_val_end(validator): # -> None:
    """Logs validation results including labels and predictions."""
    ...

def on_train_end(trainer): # -> None:
    """Logs final model and its name on training completion."""
    ...

callbacks = ...
