"""
This type stub file was generated by pyright.
"""

run = ...
def on_pretrain_routine_start(trainer): # -> None:
    """Callback function called before the training routine starts."""
    ...

def on_train_epoch_end(trainer): # -> None:
    """Callback function called at end of each training epoch."""
    ...

def on_fit_epoch_end(trainer): # -> None:
    """Callback function called at end of each fit (train+val) epoch."""
    ...

def on_val_end(validator): # -> None:
    """Callback function called at end of each validation."""
    ...

def on_train_end(trainer): # -> None:
    """Callback function called at end of training."""
    ...

callbacks = ...
