"""
This type stub file was generated by pyright.
"""

_processed_plots = ...
def on_pretrain_routine_start(trainer): # -> None:
    """Initiate and start project if module is present."""
    ...

def on_fit_epoch_end(trainer): # -> None:
    """Logs training metrics and model information at the end of an epoch."""
    ...

def on_train_epoch_end(trainer): # -> None:
    """Log metrics and save images at the end of each training epoch."""
    ...

def on_train_end(trainer): # -> None:
    """Save the best model as an artifact at end of training."""
    ...

callbacks = ...
