"""
This type stub file was generated by pyright.
"""

def build_sam_vit_h(checkpoint=...): # -> SAMModel:
    """Builds and returns a Segment Anything Model (SAM) h-size model with specified encoder parameters."""
    ...

def build_sam_vit_l(checkpoint=...): # -> SAMModel:
    """Builds and returns a Segment Anything Model (SAM) l-size model with specified encoder parameters."""
    ...

def build_sam_vit_b(checkpoint=...): # -> SAMModel:
    """Constructs and returns a Segment Anything Model (SAM) with b-size architecture and optional checkpoint."""
    ...

def build_mobile_sam(checkpoint=...): # -> SAMModel:
    """Builds and returns a Mobile Segment Anything Model (Mobile-SAM) for efficient image segmentation."""
    ...

def build_sam2_t(checkpoint=...): # -> SAM2Model:
    """Builds and returns a Segment Anything Model 2 (SAM2) tiny-size model with specified architecture parameters."""
    ...

def build_sam2_s(checkpoint=...): # -> SAM2Model:
    """Builds and returns a small-size Segment Anything Model (SAM2) with specified architecture parameters."""
    ...

def build_sam2_b(checkpoint=...): # -> SAM2Model:
    """Builds and returns a SAM2 base-size model with specified architecture parameters."""
    ...

def build_sam2_l(checkpoint=...): # -> SAM2Model:
    """Builds and returns a large-size Segment Anything Model (SAM2) with specified architecture parameters."""
    ...

sam_model_map = ...
def build_sam(ckpt=...): # -> SAMModel:
    """
    Builds and returns a Segment Anything Model (SAM) based on the provided checkpoint.

    Args:
        ckpt (str | Path): Path to the checkpoint file or name of a pre-defined SAM model.

    Returns:
        (SAMModel | SAM2Model): A configured and initialized SAM or SAM2 model instance.

    Raises:
        FileNotFoundError: If the provided checkpoint is not a supported SAM model.

    Examples:
        >>> sam_model = build_sam("sam_b.pt")
        >>> sam_model = build_sam("path/to/custom_checkpoint.pt")

    Notes:
        Supported pre-defined models include:
        - SAM: 'sam_h.pt', 'sam_l.pt', 'sam_b.pt', 'mobile_sam.pt'
        - SAM2: 'sam2_t.pt', 'sam2_s.pt', 'sam2_b.pt', 'sam2_l.pt'
    """
    ...

