"""
This type stub file was generated by pyright.
"""

from ultralytics.models import yolo

def on_pretrain_routine_end(trainer): # -> None:
    """Callback."""
    ...

class WorldTrainer(yolo.detect.DetectionTrainer):
    """
    A class to fine-tune a world model on a close-set dataset.

    Example:
        ```python
        from ultralytics.models.yolo.world import WorldModel

        args = dict(model="yolov8s-world.pt", data="coco8.yaml", epochs=3)
        trainer = WorldTrainer(overrides=args)
        trainer.train()
        ```
    """
    def __init__(self, cfg=..., overrides=..., _callbacks=...) -> None:
        """Initialize a WorldTrainer object with given arguments."""
        ...
    
    def get_model(self, cfg=..., weights=..., verbose=...): # -> WorldModel:
        """Return WorldModel initialized with specified config and weights."""
        ...
    
    def build_dataset(self, img_path, mode=..., batch=...): # -> YOLODataset | YOLOMultiModalDataset:
        """
        Build YOLO Dataset.

        Args:
            img_path (str): Path to the folder containing images.
            mode (str): `train` mode or `val` mode, users are able to customize different augmentations for each mode.
            batch (int, optional): Size of batches, this is for `rect`. Defaults to None.
        """
        ...
    
    def preprocess_batch(self, batch):
        """Preprocesses a batch of images for YOLOWorld training, adjusting formatting and dimensions as needed."""
        ...
    


