"""
This type stub file was generated by pyright.
"""

from ultralytics.models.yolo.classify.predict import ClassificationPredictor
from ultralytics.models.yolo.classify.train import ClassificationTrainer
from ultralytics.models.yolo.classify.val import ClassificationValidator

__all__ = ("ClassificationPredictor", "ClassificationTrainer", "ClassificationValidator")
