"""
This type stub file was generated by pyright.
"""

from .byte_tracker import BYTETracker, STrack

class BOTrack(STrack):
    """
    An extended version of the STrack class for YOLOv8, adding object tracking features.

    This class extends the STrack class to include additional functionalities for object tracking, such as feature
    smoothing, Kalman filter prediction, and reactivation of tracks.

    Attributes:
        shared_kalman (KalmanFilterXYWH): A shared Kalman filter for all instances of BOTrack.
        smooth_feat (np.ndarray): Smoothed feature vector.
        curr_feat (np.ndarray): Current feature vector.
        features (deque): A deque to store feature vectors with a maximum length defined by `feat_history`.
        alpha (float): Smoothing factor for the exponential moving average of features.
        mean (np.ndarray): The mean state of the Kalman filter.
        covariance (np.ndarray): The covariance matrix of the Kalman filter.

    Methods:
        update_features(feat): Update features vector and smooth it using exponential moving average.
        predict(): Predicts the mean and covariance using Kalman filter.
        re_activate(new_track, frame_id, new_id): Reactivates a track with updated features and optionally new ID.
        update(new_track, frame_id): Update the YOLOv8 instance with new track and frame ID.
        tlwh: Property that gets the current position in tlwh format `(top left x, top left y, width, height)`.
        multi_predict(stracks): Predicts the mean and covariance of multiple object tracks using shared Kalman filter.
        convert_coords(tlwh): Converts tlwh bounding box coordinates to xywh format.
        tlwh_to_xywh(tlwh): Convert bounding box to xywh format `(center x, center y, width, height)`.

    Examples:
        Create a BOTrack instance and update its features
        >>> bo_track = BOTrack(tlwh=[100, 50, 80, 40], score=0.9, cls=1, feat=np.random.rand(128))
        >>> bo_track.predict()
        >>> new_track = BOTrack(tlwh=[110, 60, 80, 40], score=0.85, cls=1, feat=np.random.rand(128))
        >>> bo_track.update(new_track, frame_id=2)
    """
    shared_kalman = ...
    def __init__(self, tlwh, score, cls, feat=..., feat_history=...) -> None:
        """
        Initialize a BOTrack object with temporal parameters, such as feature history, alpha, and current features.

        Args:
            tlwh (np.ndarray): Bounding box coordinates in tlwh format (top left x, top left y, width, height).
            score (float): Confidence score of the detection.
            cls (int): Class ID of the detected object.
            feat (np.ndarray | None): Feature vector associated with the detection.
            feat_history (int): Maximum length of the feature history deque.

        Examples:
            Initialize a BOTrack object with bounding box, score, class ID, and feature vector
            >>> tlwh = np.array([100, 50, 80, 120])
            >>> score = 0.9
            >>> cls = 1
            >>> feat = np.random.rand(128)
            >>> bo_track = BOTrack(tlwh, score, cls, feat)
        """
        ...
    
    def update_features(self, feat): # -> None:
        """Update the feature vector and apply exponential moving average smoothing."""
        ...
    
    def predict(self): # -> None:
        """Predicts the object's future state using the Kalman filter to update its mean and covariance."""
        ...
    
    def re_activate(self, new_track, frame_id, new_id=...): # -> None:
        """Reactivates a track with updated features and optionally assigns a new ID."""
        ...
    
    def update(self, new_track, frame_id): # -> None:
        """Updates the YOLOv8 instance with new track information and the current frame ID."""
        ...
    
    @property
    def tlwh(self): # -> NDArray[floating[_32Bit]]:
        """Returns the current bounding box position in `(top left x, top left y, width, height)` format."""
        ...
    
    @staticmethod
    def multi_predict(stracks): # -> None:
        """Predicts the mean and covariance for multiple object tracks using a shared Kalman filter."""
        ...
    
    def convert_coords(self, tlwh): # -> NDArray[Any]:
        """Converts tlwh bounding box coordinates to xywh format."""
        ...
    
    @staticmethod
    def tlwh_to_xywh(tlwh): # -> NDArray[Any]:
        """Convert bounding box from tlwh (top-left-width-height) to xywh (center-x-center-y-width-height) format."""
        ...
    


class BOTSORT(BYTETracker):
    """
    An extended version of the BYTETracker class for YOLOv8, designed for object tracking with ReID and GMC algorithm.

    Attributes:
        proximity_thresh (float): Threshold for spatial proximity (IoU) between tracks and detections.
        appearance_thresh (float): Threshold for appearance similarity (ReID embeddings) between tracks and detections.
        encoder (Any): Object to handle ReID embeddings, set to None if ReID is not enabled.
        gmc (GMC): An instance of the GMC algorithm for data association.
        args (Any): Parsed command-line arguments containing tracking parameters.

    Methods:
        get_kalmanfilter(): Returns an instance of KalmanFilterXYWH for object tracking.
        init_track(dets, scores, cls, img): Initialize track with detections, scores, and classes.
        get_dists(tracks, detections): Get distances between tracks and detections using IoU and (optionally) ReID.
        multi_predict(tracks): Predict and track multiple objects with YOLOv8 model.

    Examples:
        Initialize BOTSORT and process detections
        >>> bot_sort = BOTSORT(args, frame_rate=30)
        >>> bot_sort.init_track(dets, scores, cls, img)
        >>> bot_sort.multi_predict(tracks)

    Note:
        The class is designed to work with the YOLOv8 object detection model and supports ReID only if enabled via args.
    """
    def __init__(self, args, frame_rate=...) -> None:
        """
        Initialize YOLOv8 object with ReID module and GMC algorithm.

        Args:
            args (object): Parsed command-line arguments containing tracking parameters.
            frame_rate (int): Frame rate of the video being processed.

        Examples:
            Initialize BOTSORT with command-line arguments and a specified frame rate:
            >>> args = parse_args()
            >>> bot_sort = BOTSORT(args, frame_rate=30)
        """
        ...
    
    def get_kalmanfilter(self): # -> KalmanFilterXYWH:
        """Returns an instance of KalmanFilterXYWH for predicting and updating object states in the tracking process."""
        ...
    
    def init_track(self, dets, scores, cls, img=...): # -> list[Any] | list[BOTrack]:
        """Initialize object tracks using detection bounding boxes, scores, class labels, and optional ReID features."""
        ...
    
    def get_dists(self, tracks, detections): # -> NDArray[Any] | ndarray[Any, Any]:
        """Calculates distances between tracks and detections using IoU and optionally ReID embeddings."""
        ...
    
    def multi_predict(self, tracks): # -> None:
        """Predicts the mean and covariance of multiple object tracks using a shared Kalman filter."""
        ...
    
    def reset(self): # -> None:
        """Resets the BOTSORT tracker to its initial state, clearing all tracked objects and internal states."""
        ...
    


