"""
This type stub file was generated by pyright.
"""

from ultralytics.engine.model import Model

class FastSAM(Model):
    """
    FastSAM model interface.

    Example:
        ```python
        from ultralytics import FastSAM

        model = FastSAM("last.pt")
        results = model.predict("ultralytics/assets/bus.jpg")
        ```
    """
    def __init__(self, model=...) -> None:
        """Call the __init__ method of the parent class (YOLO) with the updated default model."""
        ...
    
    def predict(self, source, stream=..., bboxes=..., points=..., labels=..., texts=..., **kwargs): # -> List[Results]:
        """
        Perform segmentation prediction on image or video source.

        Supports prompted segmentation with bounding boxes, points, labels, and texts.

        Args:
            source (str | PIL.Image | numpy.ndarray): Input source.
            stream (bool): Enable real-time streaming.
            bboxes (list): Bounding box coordinates for prompted segmentation.
            points (list): Points for prompted segmentation.
            labels (list): Labels for prompted segmentation.
            texts (list): Texts for prompted segmentation.
            **kwargs (Any): Additional keyword arguments.

        Returns:
            (list): Model predictions.
        """
        ...
    
    @property
    def task_map(self): # -> dict[str, dict[str, Any]]:
        """Returns a dictionary mapping segment task to corresponding predictor and validator classes."""
        ...
    


