"""
This type stub file was generated by pyright.
"""

def adjust_bboxes_to_image_border(boxes, image_shape, threshold=...):
    """
    Adjust bounding boxes to stick to image border if they are within a certain threshold.

    Args:
        boxes (torch.Tensor): (n, 4)
        image_shape (tuple): (height, width)
        threshold (int): pixel threshold

    Returns:
        adjusted_boxes (torch.Tensor): adjusted bounding boxes
    """
    ...

