"""
This type stub file was generated by pyright.
"""

def find_free_network_port() -> int:
    """
    Finds a free port on localhost.

    It is useful in single-node training when we don't want to connect to a real main node but have to set the
    `MASTER_PORT` environment variable.
    """
    ...

def generate_ddp_file(trainer): # -> str:
    """Generates a DDP file and returns its file name."""
    ...

def generate_ddp_command(world_size, trainer): # -> tuple[list[str], str]:
    """Generates and returns command for distributed training."""
    ...

def ddp_cleanup(trainer, file): # -> None:
    """Delete temp file if created."""
    ...

