"""
This type stub file was generated by pyright.
"""

from ultralytics.engine.model import Model

class YOLO(Model):
    """YOLO (You Only Look Once) object detection model."""
    def __init__(self, model=..., task=..., verbose=...) -> None:
        """Initialize YOLO model, switching to YOLOWorld if model filename contains '-world'."""
        ...
    
    @property
    def task_map(self): # -> dict[str, dict[str, Any]]:
        """Map head to model, trainer, validator, and predictor classes."""
        ...
    


class YOLOWorld(Model):
    """YOLO-World object detection model."""
    def __init__(self, model=..., verbose=...) -> None:
        """
        Initialize YOLOv8-World model with a pre-trained model file.

        Loads a YOLOv8-World model for object detection. If no custom class names are provided, it assigns default
        COCO class names.

        Args:
            model (str | Path): Path to the pre-trained model file. Supports *.pt and *.yaml formats.
            verbose (bool): If True, prints additional information during initialization.
        """
        ...
    
    @property
    def task_map(self): # -> dict[str, dict[str, Any]]:
        """Map head to model, validator, and predictor classes."""
        ...
    
    def set_classes(self, classes): # -> None:
        """
        Set classes.

        Args:
            classes (List(str)): A list of categories i.e. ["person"].
        """
        ...
    


