"""
This type stub file was generated by pyright.
"""

from ultralytics.models import yolo

class PoseTrainer(yolo.detect.DetectionTrainer):
    """
    A class extending the DetectionTrainer class for training based on a pose model.

    Example:
        ```python
        from ultralytics.models.yolo.pose import PoseTrainer

        args = dict(model="yolo11n-pose.pt", data="coco8-pose.yaml", epochs=3)
        trainer = PoseTrainer(overrides=args)
        trainer.train()
        ```
    """
    def __init__(self, cfg=..., overrides=..., _callbacks=...) -> None:
        """Initialize a PoseTrainer object with specified configurations and overrides."""
        ...
    
    def get_model(self, cfg=..., weights=..., verbose=...): # -> PoseModel:
        """Get pose estimation model with specified configuration and weights."""
        ...
    
    def set_model_attributes(self): # -> None:
        """Sets keypoints shape attribute of PoseModel."""
        ...
    
    def get_validator(self): # -> PoseValidator:
        """Returns an instance of the PoseValidator class for validation."""
        ...
    
    def plot_training_samples(self, batch, ni): # -> None:
        """Plot a batch of training samples with annotated class labels, bounding boxes, and keypoints."""
        ...
    
    def plot_metrics(self): # -> None:
        """Plots training/val metrics."""
        ...
    


