"""
This type stub file was generated by pyright.
"""

from ultralytics.models.yolo.detect.predict import DetectionPredictor

class SegmentationPredictor(DetectionPredictor):
    """
    A class extending the DetectionPredictor class for prediction based on a segmentation model.

    Example:
        ```python
        from ultralytics.utils import ASSETS
        from ultralytics.models.yolo.segment import SegmentationPredictor

        args = dict(model="yolo11n-seg.pt", source=ASSETS)
        predictor = SegmentationPredictor(overrides=args)
        predictor.predict_cli()
        ```
    """
    def __init__(self, cfg=..., overrides=..., _callbacks=...) -> None:
        """Initializes the SegmentationPredictor with the provided configuration, overrides, and callbacks."""
        ...
    
    def postprocess(self, preds, img, orig_imgs): # -> list[Results]:
        """Applies non-max suppression and processes detections for each image in an input batch."""
        ...
    
    def construct_results(self, preds, img, orig_imgs, protos): # -> list[Results]:
        """
        Constructs a list of result objects from the predictions.

        Args:
            preds (List[torch.Tensor]): List of predicted bounding boxes, scores, and masks.
            img (torch.Tensor): The image after preprocessing.
            orig_imgs (List[np.ndarray]): List of original images before preprocessing.
            protos (List[torch.Tensor]): List of prototype masks.

        Returns:
            (list): List of result objects containing the original images, image paths, class names, bounding boxes, and masks.
        """
        ...
    
    def construct_result(self, pred, img, orig_img, img_path, proto): # -> Results:
        """
        Constructs the result object from the prediction.

        Args:
            pred (np.ndarray): The predicted bounding boxes, scores, and masks.
            img (torch.Tensor): The image after preprocessing.
            orig_img (np.ndarray): The original image before preprocessing.
            img_path (str): The path to the original image.
            proto (torch.Tensor): The prototype masks.

        Returns:
            (Results): The result object containing the original image, image path, class names, bounding boxes, and masks.
        """
        ...
    


