"""
This type stub file was generated by pyright.
"""

from ultralytics.models import yolo

class SegmentationTrainer(yolo.detect.DetectionTrainer):
    """
    A class extending the DetectionTrainer class for training based on a segmentation model.

    Example:
        ```python
        from ultralytics.models.yolo.segment import SegmentationTrainer

        args = dict(model="yolo11n-seg.pt", data="coco8-seg.yaml", epochs=3)
        trainer = SegmentationTrainer(overrides=args)
        trainer.train()
        ```
    """
    def __init__(self, cfg=..., overrides=..., _callbacks=...) -> None:
        """Initialize a SegmentationTrainer object with given arguments."""
        ...
    
    def get_model(self, cfg=..., weights=..., verbose=...): # -> SegmentationModel:
        """Return SegmentationModel initialized with specified config and weights."""
        ...
    
    def get_validator(self): # -> SegmentationValidator:
        """Return an instance of SegmentationValidator for validation of YOLO model."""
        ...
    
    def plot_training_samples(self, batch, ni): # -> None:
        """Creates a plot of training sample images with labels and box coordinates."""
        ...
    
    def plot_metrics(self): # -> None:
        """Plots training/val metrics."""
        ...
    


